services:
  mysql:
    image: mysql:8.0
    container_name: solvesync-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: solvesync
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_0900_ai_ci
    volumes:
      - solvesync_mysql:/var/lib/mysql

volumes:
  solvesync_mysql:
